N 50000
T 10
duration 0.067
diffusivity_intra 2.5e-9
diffusivity_extra 2.5e-9

scale_from_stu 1
write_txt 0
write_bin 1
write_traj_file 0
write_hit_file 0
write_full_c_file 0

num_process 24

ini_walker_pos intra
exp_prefix /home/localadmin/Documents/MCDC_perm_jas/Permeable_MCDS/results/packing/
scheme_file /home/localadmin/Documents/MCDC_perm_jas/Permeable_MCDS/docs/scheme_files/PGSE_21_dir_12_b.scheme

<obstacle>
<neurons_list>
/home/localadmin/Documents/MCDC_perm_jas/Permeable_MCDS/results/packing/_neurons_list_28_perc.txt
permeability global 0.0
sphere_overlap 4.0
</neurons_list>
</obstacle>

<voxels>
0.0 0.0 0.0
0.1 0.1 0.1 
</voxels>

<END>

