N 10
T 13860 
duration 0.077
diffusivity_intra 3e-10
diffusivity_extra 3e-10

scheme_file /home/localadmin/Documents/Rita/Codes_GitHub/Simulator_WM/Simulator_GMWM/instructions/scheme/PGSE_70_dir_high_b.scheme
exp_prefix /home/localadmin/Documents/Rita/Data/Simulations_GMWM/metab_in_teste/

<obstacle>
<axons_list>
/home/localadmin/Documents/Rita/Data/common/substracts_sims/axons.swc
permeability global 0
</axons_list>
</obstacle>
ini_walkers_pos extra

scale_from_stu 1
write_txt 0
write_bin 1
write_traj_file 1
num_process 10

<voxel>
0 0 0
0.05 0.05 0.05
</voxel>

<END>
