N 100032
T 150000
duration 0.5
diffusivity_intra 2.5e-9
diffusivity_extra 1.5e-9

scheme_file instructions/scheme/SMI.scheme
exp_prefix /home/localadmin/Documents/Projects/MCSim/outputs/f_0.5/output_extra/extra

<obstacle>
<axons_list>
/home/localadmin/Documents/Projects/MCSim/Media/f_0.5.swc
permeability global 0
</axons_list>
</obstacle>

scale_from_stu 1
write_txt 1
write_bin 1
write_traj_file 1
write_every_nth_step 1000
num_process 28
ini_walkers_pos extra

<voxel>
0 0 0
0.15 0.15 0.15
</voxel>

<sampling_area>
0.03 0.03 0.03
0.12 0.12 0.12
</sampling_area>


<END>