N 10000
T 10000
duration 0.33
diffusivity_intra 3e-9
diffusivity_extra 1e-9

scheme_file /home/localadmin/Documents/quentin_GEM/quentins_exp_d_300.scheme
exp_prefix /home/localadmin/Documents/quentin_GEM/d_300_tex_0.3_f_0.3
mix_compartment_diffusivities 1
t_ex 0.3
f 0.3

scale_from_stu 1
write_txt 0
write_bin 1
write_traj_file 0
num_process 1

<voxel>
0 0 0
0.05 0.05 0.05
</voxel>


<END>