N 10000
T 5000
duration 0.067
diffusivity_intra 2.5e-9
diffusivity_extra 1.5e-9

scheme_file /home/localadmin/Documents/quentin_GEM/test.scheme
exp_prefix /home/localadmin/Documents/quentin_GEM/test

<obstacle>
<glials_list>
/home/localadmin/Documents/quentin_GEM/test.swc
permeability global 0
</glials_list>
</obstacle>

scale_from_stu 1
write_txt 1
write_bin 1
write_traj_file 0
num_process 1
ini_walkers_pos intra


<voxel>
0 0 0
0.01 0.01 0.01
</voxel>


<END>