N 1000
T 115500
duration 0.077
diffusivity_intra 2.5e-9
diffusivity_extra 1.5e-9

scheme_file /home/localadmin/Documents/MCDS/Permeable_MCDS/instructions/scheme/SMI.scheme
exp_prefix /home/localadmin/Documents/MCDS/Permeable_MCDS/output/verif_astrocytes/axons

<obstacle>
<axons_list>
/home/localadmin/Documents/MCDS/Permeable_MCDS/output/SMI_pred/axons_astrocytes/astrocytes_0.06.swc
permeability global 0
</axons_list>
</obstacle>

scale_from_stu 1
write_txt 0
write_bin 1
write_traj_file 1
num_process 10
ini_walkers_pos intra

<voxel>
0 0 0
0.15 0.15 0.15
</voxel>

<sampling_area>
0.03 0.03 0.03
0.12 0.12 0.12
</sampling_area>


<END>